### PR TITLE
docs: add note on installing cuda version of Reactant on login nodes

### PR DESCRIPTION
**Pull request by avik-pal**

### CODE REVIEW

**Comment by wsmoses** [comment]
Hmm why is this needed?

In other words what errs presently

**Comment by avik-pal** [comment]
If you don't have internet and it tries to download the correct binary it will fail.

**Comment by avik-pal** [comment]
same as https://cuda.juliagpu.org/stable/installation/overview/#Precompiling-CUDA.jl-without-CUDA

**Comment by avik-pal** [comment]
login node gets cpu version. compute node tries to get cuda version (correctly so), and it cant download

**Pull request merged**
