### PR TITLE
Temporarily disable custom forward/backward diff rules in Enzyme-based interpreter

### PR DESCRIPTION
**Pull request by mofeing**
Let's see if this circumvents the compilation time issue while @vchuravy and @wsmoses fix the issue in Enzyme

### CODE REVIEW

**Comment by mofeing** [comment]
It seems like this doesn't circumvent the issue 🥲

**Comment by wsmoses** [comment]
sad

**Comment by wsmoses** [comment]
x/ref https://github.com/EnzymeAD/Enzyme.jl/issues/2152 if that is the same place things are beign slow [and we can borrow the same things I was using to debug perf here]

**Comment by mofeing** [comment]
fixed in #341

**Pull request closed without merging**
