### PR TITLE
Move shape information of `RArray` to field

### PR DESCRIPTION
**Pull request by mofeing**
Discussed in #52

@wsmoses Unfortunately, these commits are tangled with the move to the `Tracing.jl` file.

# Changes

- Shape information of an `RArray` will no longer be contained in a type parameter, but in a field.
- Move tracing-related code to `Tracing.jl` file.

### CODE REVIEW

**Review by wsmoses — APPROVED** [review]
This generally seems reasonable to me -- but would you be able to add the ci for benchmarking so we can test the compile time impact here?

**Comment by mofeing** [comment]
This might be hard because what needs to be measured is only the compilation time of the first execution.

Also, how should the info be displayed? Just print the timings?

**Comment by wsmoses** [comment]
@mofeing so it should be fairly easy to do this: https://github.com/EnzymeAD/Enzyme.jl/blob/main/benchmark/benchmarks.jl via https://github.com/EnzymeAD/Enzyme.jl/blob/main/.github/workflows/benchmark_pr.yml

which puts automatically a comment in the PR with the overhead change

**Comment by wsmoses** [comment]
@mofeing can you rebase this and see if benchmarking runs?

**Comment by mofeing** [comment]
I'm on it!

**Comment by mofeing** [comment]
The workflow seems to work but it's BenchmarkTools which is giving me a small headache

**Comment by mofeing** [comment]
Finally got it working.

@wsmoses I just added some basic benchmarks. Don't know if you want some more?

**Pull request merged**
