### PR TITLE
Add fallback gpu setindex

### PR DESCRIPTION
**Pull request by wsmoses**

### CODE REVIEW

**Comment by mofeing** [comment]
mmm i see why we need `mysetindex!` here but you will need to override it's behavior on the interpreter or there would be an infinite recursion right?

**Comment by wsmoses** [comment]
No because it should only ever be called with tracedrarray's

**Comment by wsmoses** [comment]
@mofeing @avik-pal so this "works" up to the point that clearly compile doesn't handle varargs. Do you mind getting this to the endpoint?

I'm sadly stuckl staring at bazel build systems =/

**Comment by wsmoses** [comment]
going to merge for now but we should fix this

**Pull request merged**
