### PR TITLE
tests: more comprehensive NN testing

### LINKED ISSUE #121: `gelu` needs to be fixed
We used a different approximation than NNlib before. Now we should change that. Tests in #110 can be marked unbroken after that

### PR DESCRIPTION
**Pull request by avik-pal**
fixes #121

### CODE REVIEW

**Comment by avik-pal** [comment]
waiting on https://github.com/LuxDL/LuxLib.jl/pull/168

**Comment by avik-pal** [comment]
Not sure why the mac tests fail. CPU and GPU both pass otherwise

**Comment by mofeing** [comment]
@avik-pal there is some package conflict on the benchmarking

**Review by wsmoses — APPROVED** [review]

**Comment by avik-pal** [comment]
> @avik-pal there is some package conflict on the benchmarking

fixed!

**Pull request merged**
