### PR TITLE
fix: bypass segfault with fill complex

### LINKED ISSUE #244: `mlirDenseElementsAttrSplatGet` with ComplexNumbers lead to a SegFault
We discussed this in the call. Here is another case for it:

```julia
using NNlib, Reactant

x = rand(ComplexF32, 4, 4)
x_ra = Reactant.to_rarray(x)
NNlib.pad_constant(x_ra, (1, 1))
@jit NNlib.pad_constant(x_ra, (1, 1))
```

```julia
[155651] signal 11 (1): Segmentation fault
in expression starting at REPL[7]:1
_ZNK4mlir9FloatAttr8getValueEv at /mnt/.julia/artifacts/0fb8e911ac752666a5be8cae1002f1b835e430b9/lib/libReactantExtra.so (unknown line)
_ZN4mlir17DenseElementsAttr3getENS_10ShapedTypeEN4llvm8ArrayRefINS_9AttributeEEE at /mnt/.julia/artifacts/0fb8e911ac752666a5be8cae1002f1b835e430b9/lib/libReactantExtra.so (unknown line)
mlirDenseElementsAttrSplatGet at /mnt/.julia/artifacts/0fb8e911ac752666a5be8cae1002f1b835e430b9/lib/libReactantExtra.so (unknown line)
mlirDenseElementsAttrSplatGet at /mnt/software/lux/Reactant.jl/src/mlir/libMLIR_h.jl:3949 [inlined]
fill at /mnt/software/lux/Reactant.jl/src/mlir/IR/Attribute.jl:446
promote_to at /mnt/software/lux/Reactant.jl/src/TracedRNumber.jl:89
pad_constant at /mnt/software/lux/Reactant.jl/ext/ReactantNNlibExt.jl:266
#pad_constant#464 at /mnt/.julia/packages/NNlib/CkJqS/src/padding.jl:100
unknown function (ip: 0x7ca1819fcb75)
pad_constant at /mnt/.julia/packages/NNlib/CkJqS/src/padding.jl:100 [inlined]
pad_constant at /mnt/.julia/packages/NNlib/CkJqS/src/padding.jl:100 [inlined]
opaque closure at ./<missing>:0
unknown function (ip: 0x7ca1819facd9)
#26 at /mnt/software/lux/Reactant.jl/src/utils.jl:148
block! at /mnt/software/lux/Reactant.jl/src/mlir/IR/Block.jl:201
unknown function (ip: 0x7ca1819cabc6)
#make_mlir_fn#20 at /mnt/software/lux/Reactant.jl/src/utils.jl:112
make_mlir_fn at /mnt/software/lux/Reactant.jl/src/utils.jl:36 [inlined]
#6 at /mnt/software/lux/Reactant.jl/src/Compiler.jl:270 [inlined]
block! at /mnt/software/lux/Reactant.jl/src/mlir/IR/Block.jl:201
#5 at /mnt/software/lux/Reactant.jl/src/Compiler.jl:269 [inlined]
mmodule! at /mnt/software/lux/Reactant.jl/src/mlir/IR/Module.jl:93
unknown function (ip: 0x7ca181955816)
#compile_mlir!#4 at /mnt/software/lux/Reactant.jl/src/Compiler.jl:266
compile_mlir! at /mnt/software/lux/Reactant.jl/src/Compiler.jl:265 [inlined]
#30 at /mnt/software/lux/Reactant.jl/src/Compiler.jl:720
context! at /mnt/software/lux/Reactant.jl/src/mlir/IR/Context.jl:76
unknown function (ip: 0x7ca18194ab56)
#compile_xla#29 at /mnt/software/lux/Reactant.jl/src/Compiler.jl:717
compile_xla at /mnt/software/lux/Reactant.jl/src/Compiler.jl:712 [inlined]
#compile#34 at /mnt/software/lux/Reactant.jl/src/Compiler.jl:744
compile at /mnt/software/lux/Reactant.jl/src/Compiler.jl:743
unknown function (ip: 0x7ca181942bfd)
jl_apply at /cache/build/builder-demeter6-6/julialang/julia-master/src/julia.h:2157 [inlined]
do_call at /cache/build/builder-demeter6-6/julialang/julia-master/src/interpreter.c:126
eval_value at /cache/build/builder-demeter6-6/julialang/julia-master/src/interpreter.c:223
eval_stmt_value at /cache/build/builder-demeter6-6/julialang/julia-master/src/interpreter.c:174 [inlined]
eval_body at /cache/build/builder-demeter6-6/julialang/julia-master/src/interpreter.c:663
jl_interpret_toplevel_thunk at /cache/build/builder-demeter6-6/julialang/julia-master/src/interpreter.c:821
jl_toplevel_eval_flex at /cache/build/builder-demeter6-6/julialang/julia-master/src/toplevel.c:943
jl_toplevel_eval_flex at /cache/build/builder-demeter6-6/julialang/julia-master/src/toplevel.c:886
eval_body at /cache/build/builder-demeter6-6/julialang/julia-master/src/interpreter.c:625
eval_body at /cache/build/builder-demeter6-6/julialang/julia-master/src/interpreter.c:539
jl_interpret_toplevel_thunk at /cache/build/builder-demeter6-6/julialang/julia-master/src/interpreter.c:821
jl_toplevel_eval_flex at /cache/build/builder-demeter6-6/julialang/julia-master/src/toplevel.c:943
jl_toplevel_eval_flex at /cache/build/builder-demeter6-6/julialang/julia-master/src/toplevel.c:886
jl_toplevel_eval_flex at /cache/build/builder-demeter6-6/julialang/julia-master/src/toplevel.c:886
ijl_toplevel_eval_in at /cache/build/builder-demeter6-6/julialang/julia-master/src/toplevel.c:994
eval at ./boot.jl:430 [inlined]
eval_user_input at /home/avikpal/.julia/juliaup/julia-1.11.1+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:245
repl_backend_loop at /home/avikpal/.julia/juliaup/julia-1.11.1+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:342
#start_repl_backend#59 at /home/avikpal/.julia/juliaup/julia-1.11.1+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:327
start_repl_backend at /home/avikpal/.julia/juliaup/julia-1.11.1+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:324
#run_repl#72 at /home/avikpal/.julia/juliaup/julia-1.11.1+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:483
run_repl at /home/avikpal/.julia/juliaup/julia-1.11.1+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:469
jfptr_run_repl_10094 at /mnt/.julia/compiled/v1.11/REPL/u0gqU_LviMe.so (unknown line)
#1139 at ./client.jl:446
jfptr_YY.1139_14655 at /mnt/.julia/compiled/v1.11/REPL/u0gqU_LviMe.so (unknown line)
jl_apply at /cache/build/builder-demeter6-6/julialang/julia-master/src/julia.h:2157 [inlined]
jl_f__call_latest at /cache/build/builder-demeter6-6/julialang/julia-master/src/builtins.c:875
#invokelatest#2 at ./essentials.jl:1055 [inlined]
invokelatest at ./essentials.jl:1052 [inlined]
run_main_repl at ./client.jl:430
repl_main at ./client.jl:567 [inlined]
_start at ./client.jl:541
jfptr__start_72144.1 at /home/avikpal/.julia/juliaup/julia-1.11.1+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
jl_apply at /cache/build/builder-demeter6-6/julialang/julia-master/src/julia.h:2157 [inlined]
true_main at /cache/build/builder-demeter6-6/julialang/julia-master/src/jlapi.c:900
jl_repl_entrypoint at /cache/build/builder-demeter6-6/julialang/julia-master/src/jlapi.c:1059
main at /cache/build/builder-demeter6-6/julialang/julia-master/cli/loader_exe.c:58
unknown function (ip: 0x7ca1b7be1e07)
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
unknown function (ip: 0x4010b8)
Allocations: 27990239 (Pool: 27988009; Big: 2230); GC: 36
[1]    155651 segmentation fault (core dumped)  julia --project=envs --threads=auto
```

### PR DESCRIPTION
**Pull request by avik-pal**
fixes #244

### CODE REVIEW

**Comment by mofeing** [comment]
great! can you add a smaller test in "complex.jl" like the following? it's the simplest case we can test this with

```julia
x = 1.0 + 2.0im
y = Reactant.ConcreteRNumber(x)

f = Reactant.compile((y,)) do z
		z + Reactant.promote_to(TracedRNumber{ComplexF64}, 1.0 - 3.0im)
end

@test isapprox(f(y), 2.0 - 1.0im)
```

(it could be simpler but parameter-less functions are broken #196)

**Comment by avik-pal** [comment]
> great! can you add a smaller test in "complex.jl" like the following? it's the simplest case we can test this with

done

**Comment by mofeing** [comment]
mmm I think you broke control flow?

**Comment by avik-pal** [comment]
oops... let me check

**Review by mofeing — APPROVED** [review]

**Pull request merged**
