### PR TITLE
ci(buildkite): fix scripts

### PR DESCRIPTION
**Pull request by avik-pal**

### CODE REVIEW

**Comment by avik-pal** [comment]
buildkite is running but it seems GPUs aren't being detected https://buildkite.com/julialang/reactant-dot-jl/builds/230#0191781a-c0c8-4ab9-9a36-867320eae25c/259-735

**Comment by avik-pal** [comment]
CUDA is detected correctly but runs into a CUDNN error https://buildkite.com/julialang/reactant-dot-jl/builds/230#0191781a-c0c6-480e-8621-d87963719344/271-744

**Comment by wsmoses** [comment]
Oh yeah i haven't tried amdgpu stuff yet (and we aren't building that on ygg atm)

**Comment by avik-pal** [comment]
```julia
E0822 08:36:00.541477 1081958 cuda_dnn.cc:535] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E0822 08:36:00.541808 1081958 cuda_dnn.cc:539] Memory usage: 859308032 bytes free, 4086169600 bytes total.
E0822 08:36:00.542929 1081958 cuda_dnn.cc:535] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E0822 08:36:00.543105 1081958 cuda_dnn.cc:539] Memory usage: 859308032 bytes free, 4086169600 bytes total.
terminate called after throwing an instance of 'xla::XlaRuntimeError'
  what():  FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
```

Even locally I am getting this. 

On a sidenote should we move ahead with #56 (but disabling more than 1 worker) that way the we can see which testitems crash without the entire test crashing

**Comment by wsmoses** [comment]
This is presently blocked by
https://github.com/JuliaPackaging/Yggdrasil/pull/9298
which is itself blocked by
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/70897

**Comment by mofeing** [comment]
CUDA infra works now. Test fails but the infra is ok.
For AMDGPU, we're getting the following error on https://github.com/EnzymeAD/Reactant.jl/blob/1ecf88d0d892c94269f9a6ab0696440bd8b7f294/test/runtests.jl#L38
```
AssertionError("Could not find registered platform with name: \"cuda\". Available platform names are: ")
```

That error seems to come from XLA.

**Comment by wsmoses** [comment]
```
Basic reduce max: Error During Test at /var/lib/buildkite-agent/builds/gpuci-2/julialang/reactant-dot-jl/test/basic.jl:29
--
  | Got exception outside of a @test
  | "Cannot setindex! to non-CPU buffer"
  | Stacktrace:
  | [1] setindex!(::ConcreteRArray{Float64, 2}, ::Float64, ::Int64, ::Int64)
  | @ Reactant /var/lib/buildkite-agent/builds/gpuci-2/julialang/reactant-dot-jl/src/ConcreteRArray.jl:163
  | [2] _setindex!
  | @ ./abstractarray.jl:1426 [inlined]
  | [3] setindex!
  | @ ./abstractarray.jl:1396 [inlined]
  | [4] fill!
  | @ ./multidimensional.jl:1123 [inlined]
  | [5] reducedim_initarray(A::ConcreteRArray{Float64, 2}, region::Int64, init::Float64, ::Type{Float64})
  | @ Base ./reducedim.jl:91
  | [6] reducedim_initarray
  | @ ./reducedim.jl:92 [inlined]
  | [7] _mapreduce_dim
  | @ ./reducedim.jl:368 [inlined]
  | [8] mapreduce
  | @ ./reducedim.jl:357 [inlined]
  | [9] reduce
  | @ ./reducedim.jl:406 [inlined]
  | [10] fastmax(x::ConcreteRArray{Float64, 2})
  | @ Main /var/lib/buildkite-agent/builds/gpuci-2/julialang/reactant-dot-jl/test/basic.jl:8
  | [11] macro expansion
  | @ /var/lib/buildkite-agent/builds/gpuci-2/julialang/reactant-dot-jl/test/basic.jl:36 [inlined]
  | [12] macro expansion
  | @ ~/.cache/julia-buildkite-plugin/julia_installs/bin/linux/x64/1.10/julia-1.10-latest-linux-x86_64/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
  | [13] top-level scope
  | @ /var/lib/buildkite-agent/builds/gpuci-2/julialang/reactant-dot-jl/test/basic.jl:30
  | [14] include(fname::String)
  | @ Base.MainInclude ./client.jl:489
  | [15] top-level scope
  | @ /var/lib/buildkite-agent/builds/gpuci-2/julialang/reactant-dot-jl/test/runtests.jl:44
  | [16] include(fname::String)
  | @ Base.MainInclude ./client.jl:489
  | [17] top-level scope
  | @ none:6
  | [18] eval
  | @ ./boot.jl:385 [inlined]
  | [19] exec_options(opts::Base.JLOptions)
  | @ Base ./client.jl:291
  | [20] _start()
  | @ Base ./client.jl:552
  | Test Summary:    \| Error  Total  Time
  | Basic reduce max \|     1      1  1.5s
  | ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broke
```

**Pull request merged**
